[build]
builder = "DOCKERFILE"

[build.env]
NIXPACKS_APT_PKGS = "libgl1 libglib2.0-0 libsm6 libxext6 libxrender1 libgomp1"

[deploy]
startCommand = "bash start.sh"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

